[package]
name = "nix-sandbox-escape-hatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.20"
systemd = "0.10.0"
tar = "0.4.40"
